query Categories($storeId: String!) {
    categories(storeId: $storeId) {
        id
        title
        description
    }
}

query Category($id: String!) {
    category(id: $id) {
        id
        title
        description
    }
}

mutation CreateCategory($storeId: String!, $data: CreateCategoryInput!) {
    createCategory(storeId: $storeId, data: $data) {
        id
        title
        description
    }
}

mutation UpdateCategory($id: String!, $data: UpdateCategoryInput!) {
    updateCategory(id: $id, data: $data) {
        id
        title
        description
    }
}

mutation DeleteCategory($id: String!) {
    deleteCategory(id: $id) {
        id
        title
        description
    }
}
