query Orders {
    orders {
        id
        tableSessionId
        status
        tableSession {
            id
            table {
                id
                name
                status
            }
        }
        items {
            id
            productId
            product {
                id
                title
                price
            }
            quantity
            unitPrice
        }
        createdAt
        updatedAt
    }
}

query Order($id: String!) {
    order(id: $id) {
        id
        tableSessionId
        status
        tableSession {
            id
            table {
                id
                name
                status
            }
        }
        items {
            id
            productId
            product {
                id
                title
                price
            }
            quantity
            unitPrice
        }
        createdAt
        updatedAt
    }
}

mutation CreateOrder($data: CreateOrderInput!) {
    createOrder(data: $data) {
        id
        tableSessionId
        status
        items {
            id
            productId
            quantity
            unitPrice
        }
    }
}

mutation UpdateOrder($id: String!, $data: UpdateOrderInput!) {
    updateOrder(id: $id, data: $data) {
        id
        tableSessionId
        status
        items {
            id
            productId
            quantity
            unitPrice
        }
    }
}

mutation DeleteOrder($id: String!) {
    deleteOrder(id: $id) {
        id
        tableSessionId
        status
    }
}
