query Products {
    products {
        id
        title
        description
        photoUrl
        price
    }
}

query Product($id: String!) {
    product(id: $id) {
        id
        title
        description
        photoUrl
        price
    }
}

mutation CreateProduct($data: CreateProductInput!) {
    createProduct(data: $data) {
        id
        title
        description
        photoUrl
        price
    }
}

mutation UpdateProduct($id: String!, $data: UpdateProductInput!) {
    updateProduct(id: $id, data: $data) {
        id
        title
        description
        photoUrl
        price
    }
}

mutation DeleteProduct($id: String!) {
    deleteProduct(id: $id) {
        id
        title
        description
        photoUrl
        price
    }
}
