query Products($storeId: String!) {
    products(storeId: $storeId) {
        id
        title
        description
        photoUrl
        price
        categoryId
        category {
            title
        }
    }
}

query Product($id: String!) {
    product(id: $id) {
        id
        title
        description
        photoUrl
        price
        categoryId
    }
}

mutation CreateProduct($storeId: String!, $data: CreateProductInput!) {
    createProduct(storeId: $storeId, data: $data) {
        id
        title
        description
        photoUrl
        price
        categoryId
    }
}

mutation UpdateProduct($id: String!, $data: UpdateProductInput!) {
    updateProduct(id: $id, data: $data) {
        id
        title
        description
        photoUrl
        price
        categoryId
    }
}

mutation DeleteProduct($id: String!) {
    deleteProduct(id: $id) {
        id
        title
        description
        photoUrl
        price
    }
}
