query Tables($storeId: String!) {
    tables(storeId: $storeId) {
        id
        name
        status
        createdAt
        updatedAt
        deletedAt
    }
}

query Table($id: String!) {
    table(id: $id) {
        id
        name
        status
        createdAt
        updatedAt
        deletedAt
    }
}

mutation CreateTable($storeId: String!, $data: CreateTableInput!) {
    createTable(storeId: $storeId, data: $data) {
        id
        name
        status
        createdAt
        updatedAt
        deletedAt
    }
}

mutation UpdateTable($id: String!, $data: UpdateTableInput!) {
    updateTable(id: $id, data: $data) {
        id
        name
        status
        createdAt
        updatedAt
        deletedAt
    }
}

mutation DeleteTable($id: String!) {
    deleteTable(id: $id) {
        id
        name
        status
    }
}
